<?xml version="1.0" encoding="utf-8"?><Database Name="MATC" Class="MATCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\MATC.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MATCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GroceryList" Member="GroceryLists">
    <Type Name="GroceryList">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>